In [1]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Downloading pandas-3.0.3-cp314-cp314-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=2.3.3 in .\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in .\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\AppData\Roaming\Python\Python314\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in .\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp314-cp314-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.9 MB 1.2 MB/s eta 0:00:08
   -- ------------------------------------- 0.5/9.9 MB 1.2 MB/s eta 0:00:08
   --- ------------------------------------ 0.8/9.9 MB 1.0 MB/s eta 0:00:09
   ---- ----------------------------------- 1.0/9.9 MB 1.1 MB/s eta 0:00:09
   ----- ---------------------------------- 1.3/9.9 MB 1.1 MB/s eta 0:00:08
   ------- -------------------------------- 1.8/9.9 MB 1.3 MB/s eta 0:00:07
   -------- ------------------------------- 2.1/9.9 MB 1.3 MB/s eta 0:00:07
   --------- ------------------------------ 2.4/9.9 MB 1.4 MB/s eta 0:00:06
   ----------- ---------------------------- 2.9/9.9 MB 1.4 MB/s eta 0:00:05
   ------------ --------------------------- 3.1/9.9 MB 1.5 MB/s eta 0:00:05
   ------------- -------------------------- 3.4/9.9 MB 1.4 MB/s eta 0:00:05
   -------------- ------------------------- 3.7/9.9 MB 1.4 MB/s eta 0:00:05
   ---------------- ----------------------- 4.2/9.9 MB 1.5 MB/s eta 0:00:04
   ------------------ --------------------- 4.5/9.9 MB 1.5 MB/s eta 0:00:04
   -------------------- ------------------- 5.0/9.9 MB 1.5 MB/s eta 0:00:04
   ---------------------- ----------------- 5.5/9.9 MB 1.6 MB/s eta 0:00:03
   ---------------------- ----------------- 5.5/9.9 MB 1.6 MB/s eta 0:00:03
   ----------------------- ---------------- 5.8/9.9 MB 1.5 MB/s eta 0:00:03
   ------------------------ --------------- 6.0/9.9 MB 1.5 MB/s eta 0:00:03
   ------------------------- -------------- 6.3/9.9 MB 1.5 MB/s eta 0:00:03
   -------------------------- ------------- 6.6/9.9 MB 1.5 MB/s eta 0:00:03
   ---------------------------- ----------- 7.1/9.9 MB 1.5 MB/s eta 0:00:02
   ------------------------------ --------- 7.6/9.9 MB 1.5 MB/s eta 0:00:02
   --------------------------------- ------ 8.4/9.9 MB 1.6 MB/s eta 0:00:01
   ----------------------------------- ---- 8.7/9.9 MB 1.6 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.9 MB 1.7 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 1.7 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 1.7 MB/s  0:00:06
Installing collected packages: pandas
Successfully installed pandas-3.0.3
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd

In [2]:
data = {'Name': [';Alice',';Bob'], 'Age': [25, 30]}

In [3]:
df = pd.DataFrame(data)

In [4]:
lst = [['Alice', 25], ['Bob', 30]]

In [5]:
df = pd.DataFrame(lst, columns=['Name', 'Age'])

In [6]:
df.head()

    Name  Age
0  Alice   25
1    Bob   30

In [7]:
df.tail()

    Name  Age
0  Alice   25
1    Bob   30

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      str
 1   Age     2 non-null      int64
dtypes: int64(1), str(1)
memory usage: 164.0 bytes

In [9]:
df.describe()

             Age
count   2.000000
mean   27.500000
std     3.535534
min    25.000000
25%    26.250000
50%    27.500000
75%    28.750000
max    30.000000

In [10]:
df['Name']

0    Alice
1      Bob
Name: Name, dtype: str

In [11]:
df[['Name', 'Age']]

    Name  Age
0  Alice   25
1    Bob   30

In [12]:
df.loc[0]

Name    Alice
Age        25
Name: 0, dtype: object

In [13]:
df.iloc[1]

Name    Bob
Age      30
Name: 1, dtype: object

In [14]:
df[df['Age'] > 25]

  Name  Age
1  Bob   30

In [15]:
df['Gender'] = ['F', 'M']

In [16]:
#df.drop('Age', axis=1, inplace=True)

In [23]:
df.isnull()

    Name    Age  Gender
0  False  False   False
1  False  False   False

In [18]:
df.dropna()

    Name  Age Gender
0  Alice   25      F
1    Bob   30      M

In [19]:
df.fillna(0)

    Name  Age Gender
0  Alice   25      F
1    Bob   30      M

In [20]:
df.groupby('Gender')['Age'].mean()

Gender
F    25.0
M    30.0
Name: Age, dtype: float64

In [26]:
df1 = pd.DataFrame({
    'key': [1, 2, 3],
    'Name': ['Anu', 'Rahul', 'Maya']
})

df2 = pd.DataFrame({
    'key': [1, 2, 3],
    'Marks': [85, 90, 88]
})

In [27]:
pd.merge(df1, df2, on='key')

   key   Name  Marks
0    1    Anu     85
1    2  Rahul     90
2    3   Maya     88

In [32]:
df1.join(df2,lsuffix='_left',rsuffix='_right')

   key_left   Name  key_right  Marks
0         1    Anu          1     85
1         2  Rahul          2     90
2         3   Maya          3     88

In [33]:
df.to_csv('data.csv',index=False)

In [34]:
df = pd.read_csv('data.csv')

In [35]:
df.to_csv('output.csv', index=False)

In [36]:
df.sort_values('Age')

    Name  Age Gender
0  Alice   25      F
1    Bob   30      M

In [37]:
df['Age'].apply(lambda x: x + 1)

0    26
1    31
Name: Age, dtype: int64

In [38]:
df['Name'].unique()

<StringArray>
['Alice', 'Bob']
Length: 2, dtype: str

In [39]:
df['Age'].value_counts()

Age
25    1
30    1
Name: count, dtype: int64